spring:
  application:
    name: costcook
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/costcook_db
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  upload:
    location: C:\\Users\\WD\\Desktop\\costcook-image
jwt:
  issuer: costcook
  secret_key: secretkeysecretkeysecretkeysecretkeysecretkey
  access_duration: 86400000
  refresh_duration: 86400000

